# Context path configuration
server:
  port: 8080
  servlet.context-path: /

# swagger-ui configurations
springdoc:
  api-docs.enabled: true
  swagger-ui:
    server-url: http://localhost:8080
    properties:
      title: Device Inventory Service
      description: API operations in DeviceRepository Inventory Service
      git-url: https://github.com/hadzhievv/hackathon-2024

# Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hackathon
    username: hackathon
    password: 12345

  # Flyway script path
  flyway:
    locations: classpath:db/local_migrations
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# B.Braun OpenId Connect Configuration
#bbraun:
#  security:
#    # Allowed origins for requests to the application
#    cors:
#      urls: http://localhost:4200