# Context path configuration
server:
  port: 8080
  servlet.context-path: /

# swagger-ui configurations
springdoc:
  api-docs.enabled: true
  swagger-ui:
    server-url: http://localhost:8080
    properties:
      title: Device Inventory Service
      description: API operations in DeviceRepository Inventory Service
      git-url: https://code.bbraun.io/IoMT/iomt-dm-di-be.git

# Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/
    username: hackathon
    password: 12345

  # Flyway script path
#  flyway:
#    locations: classpath:db/local_migrations
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

# B.Braun OpenId Connect Configuration
#bbraun:
#  security:
#    # Allowed origins for requests to the application
#    cors:
#      urls: http://localhost:4200