# Application configuration
server:
  # Server path
  servlet:
    context-path: /

# Spring configuration
spring:
  # Active profile
  profiles:
    active: local
  banner:
    location: classpath:/logo/bbraun.txt
  # Used by Actuator for telemetry
  jmx:
    enabled: true

  # Flyway configuration
  flyway:
    schemas: hackathon_2024
    enabled: true
    baseline-on-migrate: true
    table: hackathon_schema_version

  # Hibernate configuration
  jpa:
    properties:
      hibernate:
        default_schema: hackathon_2024
        jdbc.lob.non_contextual_creation: true
        enhancer:
          enableDirtyTracking: false
          enableLazyInitialization: false
    hibernate.ddl-auto: none

# Swagger-UI configurations
springdoc:
  api-docs.enabled: true
  pathsToMatch: /v*/**,/route/**
  swagger-ui:
    operationsSorter: alpha
    path: /swagger-ui.html
    tagsSorter: alpha
    properties:
      title: Device Inventory Service
      description: API operations in Device Inventory Service
      git-url: https://github.com/hadzhievv/hackathon-2024

# Actuator configurations
management:
  endpoints:
    # disable all, then enable only the needed ones
    enabled-by-default: false
    jmx:
      exposure:
        include: "health,info,metrics,env"
    web:
      exposure:
        include: "health"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true

# Application configuration
bbraun:
  tracing:
    application-code: Hackathon-2024
  # B.Braun Security Configuration
  security:
    cors:
      headers: content-type, authorization
      exposed-headers: x-platform-error-code, Location, Content-Location
    ignore:
      patterns: /**

# Application log level configuration
logging:
  level:
    #    root: DEBUG
    org:
      springframework: ERROR
    flywaydb.core.internal:
      database: ERROR
      license: ERROR